# Router implementation
import logging
from typing import Dict, Any, Coroutine

from ..interfaces.i_router import IRouter
from ..interfaces.i_tool import ITool
from ..interfaces.types import AgentRequest, ToolResult

# Configure logging
logger = logging.getLogger(__name__)

class Router(IRouter):
    """
    Manages tool registration and routes AgentRequests to the appropriate tool.
    """

    def __init__(self):
        """Initializes the Router with an empty tool registry."""
        self._tools: Dict[str, ITool] = {}
        logger.info("Router initialized.")

    def register_tool(self, tool: ITool) -> None:
        """
        Registers a tool instance with the router.

        Args:
            tool (ITool): An instance of a class implementing the ITool interface.

        Raises:
            ValueError: If a tool with the same ID is already registered or if the tool object is invalid.
        """
        if not isinstance(tool, ITool):
            raise ValueError("Invalid tool object provided. Must implement ITool.")

        tool_id = tool.id
        if not tool_id or not isinstance(tool_id, str):
             raise ValueError("Tool ID must be a non-empty string.")

        if tool_id in self._tools:
            logger.warning(f"Attempted to register tool with duplicate ID: {tool_id}")
            raise ValueError(f"Tool with ID '{tool_id}' is already registered.")

        self._tools[tool_id] = tool
        logger.info(f"Tool registered: ID='{tool_id}', Name='{tool.name}'")

    def deregister_tool(self, tool_id: str) -> None:
        """
        Deregisters a tool instance from the router.

        Args:
            tool_id (str): The unique ID of the tool to deregister.

        Raises:
            KeyError: If no tool with the given ID is found.
        """
        if tool_id not in self._tools:
            logger.warning(f"Attempted to deregister non-existent tool ID: {tool_id}")
            raise KeyError(f"Tool with ID '{tool_id}' not found.")

        del self._tools[tool_id]
        logger.info(f"Tool deregistered: ID='{tool_id}'")

    async def route_request(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """
        Routes an incoming AgentRequest to the appropriate registered tool
        and executes it asynchronously.

        Args:
            request (Dict[str, Any]): The structured request generated by the
                                      NLP parser, conforming to AgentRequest.
                                      Expected keys: 'tool_id', 'params'.

        Returns:
            Dict[str, Any]: The result from the executed tool, conforming to
                            ToolResult (e.g., {'success': True/False, ...}).
                            Returns an error structure if the tool is not found
                            or if the tool execution fails.
        """
        try:
            # Validate input against AgentRequest model
            agent_request = AgentRequest.model_validate(request)
            tool_id = agent_request.tool_id
            params = agent_request.params
            logger.info(f"Routing request for tool_id: {tool_id}")
            logger.debug(f"Request params: {params}")

            # Step 2.2.2: Tool Selection Strategy (by tool_id)
            tool = self._get_tool(tool_id)

            # Step 2.2.4: Handle "tool not found"
            if tool is None:
                logger.error(f"Tool not found for ID: {tool_id}")
                return ToolResult(success=False, error=f"Tool with ID '{tool_id}' not found.").model_dump()

            # Step 2.2.3: Invoke tool's execute
            logger.debug(f"Executing tool: {tool.name} ({tool_id})")
            tool_result_dict = await tool.execute(params=params)

            # Validate the tool's output structure before returning
            validated_result = ToolResult.model_validate(tool_result_dict)
            logger.info(f"Tool '{tool_id}' execution result: success={validated_result.success}")
            return validated_result.model_dump()

        except Exception as e:
            # Step 2.2.4: Handle tool execution errors (and validation errors)
            logger.exception(f"Error during request routing or tool execution for request: {request}")
            return ToolResult(success=False, error=f"An unexpected error occurred: {str(e)}").model_dump()


    def _get_tool(self, tool_id: str) -> ITool | None:
        """Internal helper to safely get a tool by ID."""
        return self._tools.get(tool_id)
