# Interface definition for IRouter
from abc import ABC, abstractmethod
from typing import Dict, Any, Coroutine

# Forward references for types defined elsewhere
from .i_tool import ITool
# from .types import AgentRequest, ToolResult # Uncomment when types.py is defined

class IRouter(ABC):
    """
    Abstract Base Class defining the interface for the tool router
    within the Universal Agent framework.
    """

    @abstractmethod
    def register_tool(self, tool: ITool) -> None:
        """
        Registers a tool instance with the router.

        Args:
            tool (ITool): An instance of a class implementing the ITool interface.

        Raises:
            ValueError: If a tool with the same ID is already registered.
        """
        pass

    @abstractmethod
    def deregister_tool(self, tool_id: str) -> None:
        """
        Deregisters a tool instance from the router.

        Args:
            tool_id (str): The unique ID of the tool to deregister.

        Raises:
            KeyError: If no tool with the given ID is found.
        """
        pass

    @abstractmethod
    async def route_request(self, request: Dict[str, Any]) -> Dict[str, Any]:
        """
        Routes an incoming AgentRequest to the appropriate registered tool
        and executes it asynchronously.

        Args:
            request (Dict[str, Any]): The structured request generated by the
                                      NLP parser, conforming to AgentRequest.
                                      Expected keys: 'tool_id', 'params'.

        Returns:
            Dict[str, Any]: The result from the executed tool, conforming to
                            ToolResult (e.g., {'success': True/False, ...}).
                            Returns an error structure if the tool is not found
                            or if the tool execution fails.
        """
        pass
