# Core data type definitions (AgentRequest, AgentResult, etc.)
from typing import Dict, Any, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator

# Tool-related types
ToolParams = Dict[str, Any]  # Parameters passed to a tool's execute method

class ToolResult(BaseModel):
    """
    Standard structure for the result returned by an ITool's execute method.
    """
    success: bool = Field(..., description="Indicates whether the tool execution was successful.")
    data: Optional[Any] = Field(None, description="The successful result data from the tool, if applicable.")
    error: Optional[str] = Field(None, description="An error message if the tool execution failed.")

    # Replace class Config with ConfigDict
    model_config = ConfigDict()

    # Move validation to a model_validator
    @model_validator(mode='after')
    def validate_data_error_consistency(self) -> 'ToolResult':
        """Ensure data and error fields are consistent with the success status."""
        if self.success and self.error is not None:
            raise ValueError("Error field must be None when success is True.")
        if not self.success and self.data is not None:
            raise ValueError("Data field must be None when success is False.")
        if not self.success and self.error is None:
            raise ValueError("Error field must be provided when success is False.")
        return self

# Agent-related types
class AgentRequest(BaseModel):
    """
    Standard structure for the request generated by the NLP parser.
    This is passed to the IRouter.
    """
    tool_id: str = Field(..., description="The unique identifier of the tool to be executed.")
    params: ToolParams = Field(default_factory=dict, description="The parameters extracted for the tool.")

class AgentResult(BaseModel):
    """
    Standard structure for the final result returned by the IUniversalAgent's execute method.
    """
    status: str = Field(..., description="Overall status of the command execution (e.g., 'success', 'error', 'tool_not_found').")
    result: Optional[Any] = Field(None, description="The result data if the execution was successful.")
    message: Optional[str] = Field(None, description="An informational or error message.")

    # Replace class Config with ConfigDict
    model_config = ConfigDict()

    # Move validation to a model_validator
    @model_validator(mode='after')
    def validate_result_message_consistency(self) -> 'AgentResult':
        """Ensure result and message fields are consistent with the status."""
        # Allow success with no specific result data, but maybe a message
        if self.status == 'success' and self.result is None:
            pass # Allow success with no specific result data
            
        if self.status != 'success' and self.result is not None:
            raise ValueError("Result must be None when status is not 'success'.")
        if self.status != 'success' and self.message is None:
            raise ValueError("Message must be provided when status is not 'success'.")
        return self
